"""True Financial Accounting & Reconciled Sales Extractor

Reconstructs exact sales by tracking:
1. Exact executed costs (HIRE, BUY_LAND, BUY_SEED, BUY_ANIMAL, BUY_PRODUCT).
2. Delta money per step (delta_m = next_money - cur_money).
3. Step revenue = delta_m + step_costs.
4. Attribution of step revenue to the products sold in that step's market orders.
"""

import json
import sys
from collections import defaultdict
import numpy as np

sys.path.insert(0, r"C:\Coding")
from kaggle_environments.envs.kaggriculture.kaggriculture import CROPS, ANIMALS, LAND_PRICES

FIB = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

def reconcile_financial_accounting(tape_path):
    with open(tape_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    steps = data["steps"]

    p0_reward = steps[-1][0]["reward"]
    p1_reward = steps[-1][1]["reward"]
    print(f"\n================================================================================")
    print(f"File: {tape_path}")
    print(f"True Final Rewards: P0 = ${p0_reward:,.2f} | P1 = ${p1_reward:,.2f}")
    print(f"================================================================================")

    for p_idx in [0, 1]:
        true_reward = p0_reward if p_idx == 0 else p1_reward
        
        hires_today = 0
        land_unlocks = 0
        total_costs = 0.0
        total_rev_from_delta = 0.0
        
        reconciled_sells = defaultdict(int)
        reconciled_revenue = defaultdict(float)

        for s_idx in range(len(steps)):
            s_data = steps[s_idx][p_idx]
            obs = s_data.get("observation", {})
            act = s_data.get("action", {})
            mkt = act.get("market", []) if isinstance(act, dict) else []
            
            cur_money = obs.get("farms", [{}, {}])[p_idx].get("money", 3000.0)
            if s_idx + 1 < len(steps):
                next_obs = steps[s_idx + 1][p_idx].get("observation", {})
                next_money = next_obs.get("farms", [{}, {}])[p_idx].get("money", cur_money)
            else:
                next_money = true_reward
                
            delta_m = next_money - cur_money
            
            # Step costs
            step_cost = 0.0
            # Track HIREs
            if s_idx % 24 == 0:
                hires_today = 0
                
            prices = obs.get("market", {}).get("prices", {})
            
            sell_orders = []
            for o in mkt:
                if not isinstance(o, list) or len(o) < 1:
                    continue
                cmd = o[0]
                if cmd == "HIRE":
                    cost = FIB[hires_today] if hires_today < len(FIB) else 500
                    step_cost += cost
                    hires_today += 1
                elif cmd == "BUY_LAND":
                    cost = LAND_PRICES[land_unlocks] if land_unlocks < len(LAND_PRICES) else 0
                    step_cost += cost
                    land_unlocks += 1
                elif cmd == "BUY_SEED" and len(o) >= 3:
                    item, qty = o[1], int(o[2])
                    cost = CROPS.get(item, {}).get("seed", 0) * qty
                    step_cost += cost
                elif cmd == "BUY_ANIMAL" and len(o) >= 3:
                    item, qty = o[1], int(o[2])
                    cost = ANIMALS.get(item, {}).get("cost", 0) * qty
                    step_cost += cost
                elif cmd == "BUY_PRODUCT" and len(o) >= 3:
                    item, qty = o[1], int(o[2])
                    # Quoted at market price
                    cost = float(prices.get(item, 25)) * qty
                    step_cost += cost
                elif cmd == "SELL" and len(o) >= 2:
                    item = o[1]
                    qty = int(o[2]) if len(o) > 2 else 1
                    sell_orders.append((item, qty))

            # Step revenue generated by sales = delta_m + step_cost
            step_rev = delta_m + step_cost
            if step_rev > 0:
                total_rev_from_delta += step_rev
                # Distribute step_rev to sell_orders based on quoted prices
                if len(sell_orders) == 1:
                    item, qty = sell_orders[0]
                    p = float(prices.get(item, 1))
                    actual_units = int(round(step_rev / p)) if p > 0 else 0
                    reconciled_sells[item] += actual_units
                    reconciled_revenue[item] += step_rev
                elif len(sell_orders) > 1:
                    # Multi-order step: apportion by order value
                    order_val_weights = [qty * float(prices.get(item, 1)) for item, qty in sell_orders]
                    tot_weight = sum(order_val_weights)
                    for (item, qty), w in zip(sell_orders, order_val_weights):
                        if tot_weight > 0:
                            part_rev = step_rev * (w / tot_weight)
                            p = float(prices.get(item, 1))
                            actual_units = int(round(part_rev / p)) if p > 0 else 0
                            reconciled_sells[item] += actual_units
                            reconciled_revenue[item] += part_rev

        print(f"\nPlayer {p_idx}: Starting $3,000 + Total Realized Revenue (${total_rev_from_delta:,.2f}) - Costs = Reconciled Reward: ${3000.0 + total_rev_from_delta - total_costs:,.2f}")
        print(f"Reconciled Sales Volumes:")
        for k in sorted(reconciled_sells.keys()):
            print(f"  {k:<12}: {reconciled_sells[k]:>6} units | ${reconciled_revenue[k]:>10,.2f}")

if __name__ == "__main__":
    reconcile_financial_accounting(r"C:\Coding\kaggriculture-agent\replays\93924742.json")
