import psycopg2
import pandas as pd
 
# ---------------- PostgreSQL Connection ----------------
hostname = "103.114.152.26"
port = 443
database = "metering"
username = "dhruva"
password = "tiger89moon"
 
conn = None
cursor = None
 
try:
    print("Connecting to PostgreSQL...")
 
    conn = psycopg2.connect(
        host=hostname,
        port=port,
        database=database,
        user=username,
        password=password,
        connect_timeout=30
    )
 
    print("Connection successful")
 
    cursor = conn.cursor()
 
    # ---------------- Query ----------------
    query = """
    SELECT
        task_type,
        api_key_name,
        COUNT(*) AS num_calls
    FROM public.apikey
    WHERE api_key_name IN (
       'directors@nityacare.com/english_to_marathi_voice_translation_nitya_apr_twentytwentyfive',
    'saif@ledsak.ai/ledsak',
    'gautambagulonline@gmail.com/connect',
    'bishalsaha@getpocket.money/bhasha_app',
    'harsh.mittal@tryzent.com/leoqui',
    'shubhendra.gautam@theabhyas.com/the_abhyas',
    'shivani.pandarkar@cloudodyssey.co/agentbashini',
    'srinibas.behera@retigence.com/psa',
    'vaiguru.in@gmail.com/vanimitra',
    'akankshasomvanshi7@gmail.com/na',
    'sid@scholarsadda.ai/scholarsadda',
    'ceo@digitransolutions.in/voicebot',
    'bishalsaha@getpocket.money/bhasha',
    'rajat@emergeflow.com/hindi_tts_test',
    'contact@bharatskillexchange.com/bharatskillexchange',
    'shubh.sharma0401@gmail.com/carbon_',
    'shanu.g@scholarsbox.in/scholarsbox',
    'vinamra286@gmail.com/bazar_se',
    'karangm@parinaamaa.ai/ellam_translation_key',
    'sripathy@vcollabetiq.com/vcollab',
    'ganesh.v@assisto.tech/iassisto',
    'rohan@antargyan.com/antargyan_voice_assistant',
    'ceo@farmvaidya.ai/farmvaidya',
    'avijeet@cornex.in/bhashini',
    'poojamalakar@revinotech.com/vaani',
    'it_services@monedo.in/monedo_los',
    'manish.lakra@alphadroid.io/heyalpha',
    'hiteshjohar314@gmail.com/asr_hinglish_transcription',
    'info@movingroll.com/movingroll',
    'chandan@respyr.in/respyr',
    'shridhande@gmail.com/vertexai',
    'raviteja.mullapudi@achalasolutions.com/epcr',
    'appdev@bwellhealth.in/anu',
    'shashank.hegde@o-health.in/test',
    'mahesh@effybiz.com/neoguide',
    'sameer@sentientscripts.com/sen_bhashini',
    'abhinav.vashistha132@gmail.com/signey',
    'pranav@crezam.com/crezam',
    'vishva.r@ncssoft.in/ncs_ethic_ai_api',
    'contributor@nobroker.in/sansad_bhashini_convozen',
    'manik@tongues.services/tongues',
    'venkat.naga1976@gmail.com/bhash_lifelsy',
    'akshay@offee.in/plat',
    'pradeep@indisec.com/dev_indisec',
    'vikram@seropos.app/seropos',
    'info@wsdstech.com/indic_language_chatbot',
    'ujjwal@cleandex.in/cleandex_key_bhashini',
    'rao@baapcompany.com/demo',
    'sg@coherentix.com/pratham',
    'mahsook.m.a@gmail.com/justprompt',
    'h@nileflo.com/healthflo_ulcaapikey',
    'jayasudan@deepvisiontech.ai/lets_talk_sign',
    'kaustubh.bidua@bluecoppertech.com/aktion_ai',
    'erosennin9002@gmail.com/translator',
    'smehta977202@gmail.com/akprinthub',
    'shivahr@ragavera.com/deepdub',
    'info@mobirizer.com/ohgrt',
    'nishith.shah@hotmail.com/nishkallc_app',
    'yagna@spatial.guide/ivf_treatment_notifications',
    'sanseedsofficial@gmail.com/prodigidesk_localisation',
    'hi@xpcover.com/krafts',
    'salman.a@quiddityinfotech.com/sentiment_analysis',
    'manas@bitnest.solutions/pwdraigad',
    'anand@netwrk.store/replit',
    'jathish.namboothiri@reinotechnologies.com/roombr',
    'hr@talentskout.ai/aagati_vaani',
    'anusha.bhupati@exoralabs.com/skydocai',
    'manasnaik65@gmail.com/vquantify',
    'kunalbherwani67@gmail.com/eva_apikey',
    'rao@baapcompany.com/digital_parbhani',
    'akshay@infinitypool.in/shankh',
    'pat@salk.ai/salkai_calling',
    'aaron@theleanproduct.studio/itihaas',
    'sopan.s@redbixbite.com/spell_checker',
    'maneeshk7777@gmail.com/mykey',
    'mahesh@effybiz.com/effytranslate',
    'chandan@waanee.ai/waanee',
    'support@lawe.co.in/lawe',
    'srmnikhilswn@gmail.com/nikhil_testing',
    'amitha.surabhi@maiora.co/amdemo',
    'suresh@byasatech.com/swasth_kadam',
    'ankita.ia025@gmail.com/verity',
    'nagarajbhat0011@gmail.com/kavi_keyboard',
    'vipendra@qollabb.com/voice_ai_project_guide',
    'shalinipareek02@gmail.com/krishi_mitra',
    'vishva.r@ncssoft.in/multilingualdocumentprocessing',
    'info@blysshealthtech.com/bconsent_a',
    'vaibhaw@saninnvotech.com/predictor',
    'nitin@karya.in/spotlight',
    'info@krishvatech.com/ai_voice_agent',
    'venkatesang@aurelionfutureforge.com/dpdp_consent_platform',
    'bhagavan@promptlyai.in/promptlyai_translater',
    'yakub@annadata.ai/annadata',
    'ajay.mahiwal@tcbinfotech.co.in/nms',
    'parimal.maldhure@nimbusnext.com/bhashantaran',
    'shashwatsinha@smartdatainc.net/smartcare',
    'amey.shinde@bizzencecollab.com/kyndryl_hackathon_api_key',
    'lavp.yiion@gmail.com/yiionchatbot',
    'ravindra@qocial.org/qocial',
    'info@hru.today/hru_today_app',
    'shubham@guideus.in/guideus',
    'bhashini@paynearby.in/saathi_uat',
    'mss@aicahealth.com/aicahealth',
    'admin@unitedpro.in/anveshak',
    'developer@nitinnovtech.com/confidento_ai',
    'bhashini@paynearby.in/paynearby',
    'neil@mapmycrop.com/mmcapp',
    'ayush.jha@vidzai.com/mlai',
    'abhilash@fintaar.ai/fintaarvoice',
    'it-desk@fujisakuratech.com/dentalapplication',
    'vishal.pandey@lumiq.ai/tmer',
    'nehruraj4ai@gmail.com/clinicalconsulting',
    'connect@byteelephants.com/api_key_tts',
    'devipriya@nexshift.ai/collectionandservice',
    'sushantpandey6203@gmail.com/satyuktvirtualassistant',
    'product.support@tensorgo.com/testapi',
    'nidhish.rajan.strategy@gmail.com/s_ai',
    'admin@icuraconnect.com/icuraconnect',
    'sanseedsofficial@gmail.com/prodigidesk_production',
    'prajwalgenious@gmail.com/sahayak_ai_voice_assistant',
    'admin@aparsoft.com/aparailms',
    'chilarai@wreken.com/borolang',
    'tech@aguken.com/aguken_ai',
    'webmaster@datacomp.in/imagic',
    'cloudadmin-ekstep-sb@kenpath.io/oanamul',
    'raman.pathak@oriserve.com/voicegenietest',
    'srinisinternational@gmail.com/auravox',
    'ajayaj@elvicto.in/parkochi',
    'info@quore-tex.com/crm_gadchiroli',
    'manmeet@gotraze.com/traze_ai',
    'laxman.hedaoo@bootcoding.in/aceint',
    'helloprachipandey@gmail.com/moodsense',
    'ashwin@mittarv.com/scambuster_dev',
    'ajayaj@elvicto.in/winpark',
    'bhagyashree.sharma@elisiontec.com/testing',
    'hb@teamkarimganj.com/ragika',
    'ashok.vadhel@gmail.com/translations',
    'avishetty2001@gmail.com/local_ai_poc',
    'venkatesh@apnavikas.com/apna_vikas',
    'rohith@unverse.in/linkup_speakeasy',
    'kishorrathod@worthitcs.com/bmc',
    'sanikommu111@gmail.com/renterspace',
    'director@net-zoop.com/netzoop',
    'sanchar@dev-vani.com/vaani_ai',
    'hello@zupaloop.com/zupaloop',
    'titus@zoifintech.com/jade_wealth_app',
    'cloudadmin-ekstep-sb@kenpath.io/oanbharatvistaar',
    'digichikitsak@gmail.com/dev',
    'support@sikhoeasy.com/sikhoeasy',
    'connect@cloudfoxx.com/finpulz',
    'sudhirs@cloudbuilders.io/cbt',
    'hello@techity.ai/sikhoeasy',
    'chandra.pradhan@risointelligence.in/grivance_chatbot',
    'chitrasuresh@pcpractoacademy.com/video_translator_app',
    'diwakar@prepaud.com/prepaud_test',
    'ranjithkumar8352@gmail.com/deva',
    'founders@fawda.in/fawda',
    'director@dairaedtech.in/jiveesha',
    'administrator@stockwatch.live/stockwatch',
    'info@blysshealthtech.com/bconsent',
    'krupa@agribridge.in/krishivaas_openai_chatbot',
    'ravin@kaigal.com/kaigalbhasini',
    'kvs@genbioca.com/moringa',
    'kunal@pehchaan.me/pehchaan',
    'rajesh@i-resonate.com/iresonate',
    'admin@ahomlama.com/universaltestkey',
    'support@bossma.in/naribot',
    'raghavendra.krishna@mapmyindia.com/mapmyindia_test_keys',
    'sthakkar@everlign.com/marathitranslation',
    'ninadssumant@gmail.com/e_suvidha',
    'vikas.kasture@globalion.in/bharateseva',
    'intrvuz@gmail.com/intrvuz',
    'ananth@iamdave.ai/daveai',
    'monesh@zautoai.com/genemr',
    'abhinav.singh@jaxl.com/jaxl_dev',
    'pratyusha.r@kheyti.com/farmeradvisory',
    'darylperis.cm@gmail.com/hindi_speech_recognition_api',
    'sharma.avish@prodigylegal.com/prodigyapp',
    'vijayendrarahul.97@gmail.com/demo',
    'naveenreddy@neurom.in/shortly',
    'aiflux2024@gmail.com/laphu',
    'support@axzoragroup.com/voicebot',
    'ronit@siva.sh/siva_sh',
    'devipriya@nexshift.ai/collection',
    'infohrtmedia@gmail.com/taniniram',
    'puneet@flexrad.ai/flexreport',
    'bhuvana@mevn.ai/mevnai',
    'smita@5xtechnologies.in/ghoshak',
    'azhar@theaccura.com/tts_app',
    'anand@netwrk.store/bhashanotes',
    'premanart@gmail.com/instabill',
    'somesh@wordworksai.com/bhashinitelugu',
    'sueb@neetgpt.in/neetgptapi',
    'vamshirathnaa@prabodh.in/mlgl_translator',
    'uday@spellwellindia.com/spellwellindia',
    'info@gaugrace.com/gaugrace',
    'arvind@medlio.ai/medlio',
    'ganesh.v@assisto.tech/assisto',
    'manishkumar10930@gmail.com/mintmenu',
    'vikas.maddheshiya@nimbusnext.com/bhashantran',
    'support@prabodh.in/prabodh',
    'info@visiorg.com/mahakumbha',
    'nishant@abetterlogic.com/manavsetu',
    'vaishakhsk2052@gmail.com/multilingual_voice_assistant',
    'info@wejan.co.in/wejan',
    'amey.shinde@bizzencecollab.com/apikeyone',
    'tech@kisanmitra.ai/internal_crm',
    'saurabh@ima-appweb.com/dtc_tpms',
    'ranjeet@cetpainfotech.com/purosangh',
    'joseph.samuel@droog.io/droogassist',
    'developer@gravitas.ai/voice_bot_api',
    'kishore.dasari@amitekh.com/amiassistant',
    'vikas.maddheshiya@nimbusnext.com/dhvani_bhashantran',
    'yoganandaj@siyoratech.com/siyora_ai_search_engine',
    'divya@flipr.ai/translation_key',
    'contact@aryamindtech.com/admission_counselling',
    'priyamarora55@gmail.com/signisl',
    'vijayendrarahul.97@gmail.com/hindi_to_text',
    'info@digitalneurones.ai/adhyayanai',
    'zspldev@zapurzaasystems.com/indoscribe',
    'mumal@edunova.one/recruit_interview_api',
    'vishal@bitloka.com/campustrack',
    'abhijit@hlthtek.com/htmate',
    'amani@macrocosmoscreations.com/mcc_farm_fusion',
    'shashankv099@gmail.com/test',
    'vikas.maddheshiya@nimbusnext.com/yavi_bhasantaran',
    'dhruvaraju.aitabathula@covasant.com/translation_app',
    'mayur.karwa@eshopbox.com/eshopbox_failed_delivery_voice_bot',
    'sid@scholarsadda.ai/scholars_adda',
    'info.reporgo@gmail.com/reporgo',
    'tech@learningmatters.xyz/tara_app',
    'ceo@krishnasdigitech.in/emergency_cyber_helpline',
    'vijayendrarahul.97@gmail.com/stt',
    'santosh.shankar@va-ak.app/vaak',
    'rhitrao@gmail.com/kannadastsapp',
    'sharmaabhi21anu@gmail.com/visit_module_translator',
    'eshalabsllp@gmail.com/sankalpa',
    'shravan.bardwa@boltware.in/boltware',
    'dolphin64819@mailshan.com/randomapp',
    'sundeep@resilience360.ai/reshype',
    'priyanka@plutos.one/csc_billpaymentlite',
    'ashok.vadhel@gmail.com/translation',
    'sekhar@cartoon.movie/cartoon_movie',
    'laher@aiveda.io/aiveda',
    'pranit.malik@karkinos.in/jiohealth',
    'subachandran@finsightanalytics.org/baashini',
    'sauravxzent@proton.me/mahaconnect',
    'vishwam@digilr.com/digilr',
    'support@arianus.in/edutask_multilang',
    'ashok.im@vidarka.com/ramaraj',
    'anand@takingforward.com/learning_speech',
    'akash@achttien.io/indialm',
    'setdiwakar@gmail.com/tunk',
    'founder@scholarsync.ai/scholarsync',
    'nagarajbhat0011@gmail.com/kavi',
    'shriniket@osvi.ai/voice_app',
    'rnkoley.softway@hotmail.com/ipis',
    'kreddy@sadhaka.ai/sadhaka',
    'bala@kartoffel.in/digidoc',
    'chatbot@haqdarshak.com/chatbot',
    'pratik@autom-axis.com/indian_language',
    'ibrahim.khatri@privezi.ai/privezi_consent_regional_language',
    'vvkannan512@gmail.com/ai_health_chatbot',
    'sales@subhahu.com/reztrans',
    'subhashbantawa.in@gmail.com/prexa',
    'nishant.jain@elderfly.com/elderfly_chatbot',
    'nivasyncinfotech@gmail.com/iriset',
    'vivek.bansal@earnest-fintech.co.in/digidukan_ondc',
    'pradeep@devseccops.ai/voice_chatbot',
    'tushar@arcaai.com/audio_service_app',
    'sheetal@uptroop.io/uptroop_vernacular',
    'apprioinfo@gmail.com/riopos',
    'vvkannan512@gmail.com/kalvi_world',
    'naresh.n@protecciodata.com/proteccio_ropa',
    'irajbirbhardwaj@gmail.com/gantavya',
    'admin@atg.world/across_the_globe',
    'ajay.patel@f22labs.com/voxi',
    'jollyhires.dev@gmail.com/tourist_translation',
    'dhruvbakshi@schooldost.in/school_dost',
    'blossom.kawatra@astra.xlri.ac.in/sarth',
    'pjain247jp@gmail.com/bhashinibert',
    'support@flexiesuite.com/flexie_erp',
    'khamir@lexiconn.in/lexaudit',
    'abhijitmalik40@gmail.com/odia_translation',
    'akuvan@akumenai.com/insights',
    'ceo@finkhoz.com/finkhoz',
    'smridhgupta007@gmail.com/ai_chatbot',
    'projectshub@codeflixglobal.com/grama_vani',
    'sunil@chatbucket.chat/chatbucket',
    'swetanks@jobsyahan.com/jobsyahan',
    'srinivasan.k@acwcircle.com/testkey',
    'jay@indilingo.in/bhashini_indilingo_api_key',
    'sharad@mashmari.in/mashmari_llp',
    'mathinaa2000@gmail.com/tts',
    'ayush.jha@vidzai.com/speechtospeech',
    'hmopuri@aapnainfotech.com/ea_aura_tts',
    'upama.mukhopadhyay@trustt.com/trusttai_demo',
    'vivek@pseudoclan.com/kamaikavachapp',
    'support@monkdb.com/monkdb_mcp',
    'samartharora176@gmail.com/testing',
    'ag@parinaamaa.ai/naamaa',
    'saravana@smartchainers.com/demo_voice',
    'pradeepk@xbosonai.in/krishisat',
    '72web.developer@gmail.com/bhasini_translate',
    'operations@intellidata.in/speech_api',
    'amish.saneen@healthplix.com/halo_test',
    'retheesh@vitalstatzz.com/sixense',
    'magfurrume.tiller@gmail.com/videomake',
    'miracledrinks4@gmail.com/miracle_transfer',
    'namratha.ar@softsurge.tech/shastranveshi',
    'coolcool.shalini@gmail.com/wandergenie',
    'mkpammi@gmail.com/vidmarg_key',
    'maneeshk7777@gmail.com/genlang',
    'vuetech8@gmail.com/iist_api',
    'abhijaiswal308@gmail.com/voiceover_automation',
    'suja.sharma@codepackers.com/alaap',
    'aditya.satya@tihiitb.org/tihstbl',
    'prasath.manohar@fluidflow.ai/fluidflowai',
    'bishalboss557@gmail.com/bhasha',
    'mitesh.mewada@lakhuteleservices.com/callex',
    'cloudadmin-ekstep-sb@kenpath.io/openagrinet',
    'santosh.shankar@va-ak.app/vaak_one',
    'abhishek.porwal@edenedge.in/geenius',
    'vedanshgoswami36@gmail.com/release',
    'rudra@boompanda.in/fifthsense',
    'patelaryan2005k@gmail.com/aisalescopilot',
    'vimalk179@gmail.com/multilingual_translator',
    'smrutisikhabramha@gmail.com/civic_issue',
    'saurabh.verma@tekmindz.com/tmz_chatbot',
    'appbuddyllp@gmail.com/goa_app',
    'tanmay.talekar1@gmail.com/saathi',
    'abhilash@fintaar.ai/fintaar_voice',
    'gulshan@pragyaa.ai/stt',
    'surajsalimath87@gmail.com/clinicsyncai',
    'hello@consently.in/consently',
    'sekhar@cartoon.movie/bhashini_tts',
    'admin@topperias.com/adaptiq_topperias',
    'vikram.tewari@workassist.in/workassist',
    'rajat@myupchar.com/myupchar',
    'ranjan.relan@agentanalytics.ai/msme_key',
    'director@zeekerstech.com/zeek_vehicle_track',
    'h@nileflo.com/sangamai',
    'vishwa@coschool.ai/coschool_testing',
    'abhinavdubey3460@gmail.com/bamu',
    'ashirbad@hermitlabs.in/readabled',
    'pisupathigowri@gmail.com/asha',
    'dk.yadav@hexwireless.com/mfluence',
    'amit@1commerce.app/newapp',
    'kaushikdipane@gmail.com/demoapplication',
    'naresh.n@protecciodata.com/proteccio_data_website',
    'rajendra.biswal@gmail.com/netzooptranslate',
    'dev@strangify.com/telanganagov',
    'manzoornel@gmail.com/medinoteai',
    'jvelectromech@gmail.com/ridebharat',
    'vivek@yugasa.com/yugasa_bot',
    'help.cinevestor@gmail.com/cinevestor',
    'pradeep@indisec.com/qa_indisec',
    'anand@netwrk.store/bhashacode',
    'sparrowsoftechpvtltd@gmail.com/nwcmc_citizen_portal',
    'raghib@pixaflip.com/speechtospeech',
    'pranav@carnotresearch.com/text_translation',
    'keshavbhatia07@gmail.com/vaanisanket',
    'basavaraj@someshwara.com/vexhibit_bhashini_key',
    'info@srashtasoft.com/ai_voice_agent',
    'shashankv099@gmail.com/ohealth',
    'kpadmaja.jaleti@gmail.com/pmf',
    'rohit@hirestar.io/aivoice_assistant',
    'vkasture@globalion.in/bharatesevakendra',
    'admin@sportechinnolab.org/sportskeyz',
    'ziyadkomakkal@gmail.com/robo',
    'info@blysshealthtech.com/bconsentprod',
    'kshitij.patil@aadrila.com/bhashasetu',
    'statsbased22@gmail.com/prexa',
    'ashutosh@indiagold.co/call_summary_agent',
    'ambrish.a@global-value-web.com/testingframework',
    'commercial@sapidblue.com/sapidblue_ecrp'
    )
    GROUP BY task_type, api_key_name
    ORDER BY num_calls DESC
    """
 
    print("Executing query...")
    cursor.execute(query)
 
    print("Fetching results...")
    rows = cursor.fetchall()
 
    df = pd.DataFrame(
        rows,
        columns=[
            "task_type",
            "api_key_name",
            "num_calls"
        ]
    )
 
    print("\nResult Preview:")
    print(df.head())
 
    output_file = "output.csv"
 
    df.to_csv(
        output_file,
        index=False
    )
 
    print(f"\nData saved successfully: {output_file}")
    print(f"Total records: {len(df)}")
 
except Exception as e:
    print("\nERROR:")
    print(str(e))
 
finally:
    if cursor:
        cursor.close()
 
    if conn:
        conn.close()
 
    print("PostgreSQL connection closed")